### ISSUE TITLE
Error: exception: undefined method `sort' for nil:NilClass

### ISSUE THREAD

**Issue by MrMoronIV** [obazoud/sensu-plugins-kafka#24]
I have ACL enabled on my kafka cluster and try to use:
``` 
./metrics-consumer.rb -g readMsg
```
It gives back:
```
Error: exception: undefined method `sort' for nil:NilClass
```

The group exists, do I need to give permissions to a specific user or what is the approach I need to take? Using confluent-kafka version 5.3.1 (latest as of now)

**Comment by MrMoronIV** [comment]
Same for, but with more error output:

```
 ./check-consumer-lag.rb -g readMsg
```

```
Error: exception: undefined method `sort' for nil:NilClass - ["/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-kafka-0.12.2/bin/check-consumer-lag.rb:68:in `kafka_topics'", "/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-kafka-0.12.2/bin/check-consumer-lag.rb:93:in `run'", "/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugin-1.4.7/lib/sensu-plugin/cli.rb:58:in `block in <class:CLI>'"]
ConsumerLagCheck CRITICAL
```

**Comment by obazoud** [comment]
It is related to this line https://github.com/obazoud/sensu-plugins-kafka/blob/master/bin/check-consumer-lag.rb#L68
Maybe the kafka consumer group does not exist.

**Comment by MrMoronIV** [comment]
As I said, the group exists. Plaintext is not enabled, only SASL and SSL_SASL, I guess I need ti authenticate somehow?
